apiVersion: v1
kind: Service
metadata:
  name: svc-flask
spec:
  type: NodePort
  selector:
    app: flask-quake-watch
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: flask-quake-watch
  labels:
    app: flask-quake-watch
spec:
  containers:
  - image: lironyo98/flask_quakeqatch:0.2.0
    name: quake-watch-container